from typing import TYPE_CHECKING, Any, Callable, Self

import PySide6.QtCore as QtCore


class Property[T](QtCore.Property):
    type Getter = Callable[[Any], T]
    type Setter = Callable[[Any, T], None]
    type Notifier = QtCore.Signal | Callable[[Any], None]
    type Deleter = Callable[[Any], None]

    if TYPE_CHECKING:
        def __init__(self, type: type[T],
                     fget: Getter | None = ..., fset: Setter | None = ...,
                     freset: Setter | None = ..., notify: Notifier | None = ...,
                     doc: str = ..., designable: bool = ..., scriptable: bool = ...,
                     stored: bool = ..., user: bool = ...,
                     constant: bool = ..., final: bool = ...) -> None: ...

        def __get__(self, instance: Any, owner: Any) -> T: ...
        def __set__(self, instance: Any, value: T) -> None: ...
        def __call__(self, func: Getter | Setter) -> Self: ...
        def deleter(self, fdel: Deleter) -> Self: ...
        def getter(self, fget: Getter) -> Self: ...
        def read(self, fget: Getter) -> Self: ...
        def setter(self, fset: Setter) -> Self: ...
        def write(self, fset: Setter) -> Self: ...
